# Generated by Django 2.2.2 on 2019-06-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('dt_nacimento', models.DateField()),
                ('vivo', models.BooleanField(default=True)),
                ('pais_origem', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('editora', models.CharField(max_length=50)),
                ('dt_lancamento', models.DateField()),
                ('preco', models.DecimalField(decimal_places=2, default=30, max_digits=10)),
                ('paginas', models.IntegerField()),
                ('idioma', models.CharField(max_length=30)),
                ('resumo', models.TextField(default='')),
                ('genero', models.CharField(choices=[('tr', 'terror'), ('rm', 'romance'), ('aj', 'autoajuda'), ('av', 'aventura'), ('mg', 'mangá'), ('hq', 'historia em quadrinhos'), ('bg', 'biogtrafia')], max_length=2)),
                ('nome', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='meuapp.Autor')),
            ],
        ),
    ]
